function count_mentions
     echo "Directory | Count"                                                                                                                                                                                                                                                                                                                                                     
     echo "-----------------"                                                                                                                                                                                                                                                                                                                                                     
     for dir in (find . -type d)                                                                                                                                                                                                                                                                                                                                                  
         set count (grep -r "TODO" $dir | wc -l)                                                                                                                                                                                                                                                                                                                                  
         if test $count -gt 0                                                                                                                                                                                                                                                                                                                                                     
             set date (date)
             echo "$dir | $count | $date"                                                                                                                                                                                                                                                                                                                                                 
         end                                                                                                                                                                                                                                                                                                                                                                      
     end | column -t -s '|'                                                                                                                                                                                                                                                                                                                                                       
 
end
